name: medicine
channels:
  - defaults

dependencies:
  - python=3.13
  - pip

  - pip:
      - numpy==2.4.1
      - pandas==3.0.0
      - matplotlib==3.10.8
      - pillow==12.1.0

      # DL / GPU
      - torch
      - torchvision