# 공통 경로 설정
# 모든 경로는 "프로젝트 루트 기준 상대경로"로 작성

# 데이터 관련 경로
data:
  processed: data/processed
  test_images: data/raw/test_images
  train_annotations: data/raw/train_annotations
  train_images: data/raw/train_images

# 데이터셋 관련
dataset:
  yolo_dataset: dataset/yolo_dataset  # YOLO 변환 데이터셋 저장 위치
  yolo_dataset_aug: dataset/yolo_dataset_aug
